#Requires -Version 7.4

$ErrorActionPreference = 'Stop'

function Get-ReleasePlan {
    <#
    .SYNOPSIS
        Resolve a merged PR's version, commit, and release notes.
    .DESCRIPTION
        Accept only closed, merged PRs targeting this repository's main branch.
        Interpret canonical numeric tags and bump labels without executing PR text.
    .EXAMPLE
        Get-ReleasePlan -WebhookEvent $payload -TagName @('0.0.9', '0.0.10')
    .OUTPUTS
        System.Management.Automation.PSCustomObject
    #>
    [OutputType([PSCustomObject])]
    [CmdletBinding()]
    param(
        # Parsed GitHub webhook payload.
        [Parameter(Mandatory)]
        [System.Collections.IDictionary] $WebhookEvent,

        # All repository tag names, not just tags with published releases.
        [Parameter(Mandatory)]
        [AllowEmptyCollection()]
        [string[]] $TagName
    )

    $pr = $WebhookEvent.pull_request
    if ($WebhookEvent.action -cne 'closed' -or $pr.merged -ne $true -or
        $WebhookEvent.repository.full_name -cne 'ClaweOfTheWild/Wild' -or
        $pr.base.repo.full_name -cne 'ClaweOfTheWild/Wild' -or $pr.base.ref -cne 'main') {
        Write-Verbose 'Skip event: not a merged PR targeting ClaweOfTheWild/Wild main.'
        return
    }
    if ($pr.merge_commit_sha -cnotmatch '^[0-9a-f]{40}$') {
        throw 'The merged PR must provide a full merge commit SHA.'
    }
    if ($pr.number -isnot [long] -and $pr.number -isnot [int] -or $pr.number -le 0) {
        throw 'The merged PR must provide a positive integer PR number.'
    }
    if ([string]::IsNullOrWhiteSpace($pr.title)) {
        throw 'The merged PR must provide a title.'
    }

    $labels = @($pr.labels.name | Where-Object { $_ -cin @('release:major', 'release:minor', 'release:patch') })
    if ($labels.Count -gt 1) {
        throw 'Multiple release labels are not allowed. Select zero or one bump label before merging.'
    }
    $bump = 'patch'
    if ($labels.Count -eq 1) {
        $bump = $labels[0].Substring('release:'.Length)
    }

    $versions = @(
        foreach ($name in $TagName) {
            if ($name -cmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$') {
                [PSCustomObject] @{
                    Major = [bigint] $Matches[1]
                    Minor = [bigint] $Matches[2]
                    Patch = [bigint] $Matches[3]
                }
            }
        }
    )
    if ($versions.Count -eq 0) {
        throw 'No stable X.Y.Z tags exist. Restore the version baseline before publishing.'
    }
    $latest = $versions | Sort-Object -Property Major, Minor, Patch -Descending | Select-Object -First 1
    switch ($bump) {
        'major' {
            $latest.Major += 1
            $latest.Minor = 0
            $latest.Patch = 0
        }
        'minor' {
            $latest.Minor += 1
            $latest.Patch = 0
        }
        'patch' {
            $latest.Patch += 1
        }
    }
    $body = $pr.title
    if (-not [string]::IsNullOrEmpty($pr.body)) {
        $body += "`n`n" + $pr.body
    }
    [PSCustomObject] @{
        Version = "$($latest.Major).$($latest.Minor).$($latest.Patch)"
        CommitSha = $pr.merge_commit_sha
        PullRequestNumber = $pr.number
        Body = $body
    }
}

function Invoke-ReleaseRequest {
    <#
    .SYNOPSIS
        Call the repository's GitHub REST API with JSON data.
    .DESCRIPTION
        Keep the token at the transport boundary and distinguish an optional 404
        from permission errors, rate limits, conflicts, and service failures.
    .EXAMPLE
        Invoke-ReleaseRequest -Method GET -Path 'tags?per_page=100&page=1'
    .OUTPUTS
        System.Object
    #>
    [OutputType([object])]
    [CmdletBinding()]
    param(
        # Only operations required by the release transaction are supported.
        [Parameter(Mandatory)]
        [ValidateSet('GET', 'POST')]
        [string] $Method,

        # A repository-relative API path generated by the publisher.
        [Parameter(Mandatory)]
        [ValidatePattern('^(tags\?|git/|releases)')]
        [string] $Path,

        # JSON request data; never shell source.
        [Parameter()]
        [hashtable] $Body,

        # Only release lookup may legitimately return 404.
        [Parameter()]
        [switch] $AllowNotFound
    )

    $token = [Environment]::GetEnvironmentVariable('GH_TOKEN')
    if ([string]::IsNullOrWhiteSpace($token)) {
        throw 'GH_TOKEN is required for the release API.'
    }
    $parameters = @{
        Uri = "https://api.github.com/repos/ClaweOfTheWild/Wild/$Path"
        Method = $Method
        Headers = @{
            Authorization = "Bearer $token"
            Accept = 'application/vnd.github+json'
            'X-GitHub-Api-Version' = '2022-11-28'
        }
        SkipHttpErrorCheck = $true
        TimeoutSec = 60
        MaximumRedirection = 0
    }
    if ($null -ne $Body) {
        $parameters.ContentType = 'application/json; charset=utf-8'
        $parameters.Body = [Text.Encoding]::UTF8.GetBytes(($Body | ConvertTo-Json -Depth 20 -Compress))
    }
    $response = Invoke-WebRequest @parameters
    if ($response.StatusCode -eq 404 -and $AllowNotFound -and $Method -eq 'GET') {
        return
    }
    if ($response.StatusCode -lt 200 -or $response.StatusCode -ge 300) {
        throw "GitHub $Method $Path failed (HTTP $($response.StatusCode)). Resolve the error and rerun this workflow."
    }
    $response.Content | ConvertFrom-Json -AsHashtable
}

function Publish-MergedPullRequestRelease {
    <#
    .SYNOPSIS
        Reserve and publish exactly one version for a merged PR.
    .DESCRIPTION
        The workflow serializes callers. An annotated tag durably records PR
        ownership before publishing, so reruns can finish partial transactions.
        Existing tags and releases are never updated or deleted.
    .EXAMPLE
        Publish-MergedPullRequestRelease -WebhookEvent $payload
    .EXAMPLE
        Publish-MergedPullRequestRelease -WebhookEvent $payload -WhatIf
    .OUTPUTS
        System.Management.Automation.PSCustomObject
    #>
    [OutputType([PSCustomObject])]
    [CmdletBinding(SupportsShouldProcess)]
    param(
        # The original closed-PR event, including its merge-time notes and labels.
        [Parameter(Mandatory)]
        [System.Collections.IDictionary] $WebhookEvent
    )

    # Validate the event before contacting GitHub. The real tag set is read below.
    $eligible = Get-ReleasePlan -WebhookEvent $WebhookEvent -TagName @('0.0.0')
    if ($null -eq $eligible) {
        return
    }

    $tags = [Collections.Generic.List[object]]::new()
    $page = 1
    do {
        $batch = @(Invoke-ReleaseRequest -Method GET -Path "tags?per_page=100&page=$page")
        foreach ($tag in $batch) {
            $tags.Add($tag)
        }
        $page++
    } while ($batch.Count -eq 100)

    $plan = Get-ReleasePlan -WebhookEvent $WebhookEvent -TagName @($tags | ForEach-Object { $_.name })
    $marker = "Wild release for ClaweOfTheWild/Wild#$($plan.PullRequestNumber)`nCommit: $($plan.CommitSha)"
    $existingTags = @($tags | Where-Object {
        $_.name -cmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' -and
        $_.commit.sha -ceq $plan.CommitSha
    })
    if ($existingTags.Count -gt 1) {
        throw 'Multiple version tags point to this merge commit. Refusing an ambiguous release.'
    }
    if ($existingTags.Count -eq 1) {
        $plan.Version = $existingTags[0].name
        $ref = Invoke-ReleaseRequest -Method GET -Path "git/ref/tags/$($plan.Version)"
        if ($ref.object.type -cne 'tag') {
            throw 'The existing version tag is not owned by this PR. Refusing to overwrite it.'
        }
        $annotation = Invoke-ReleaseRequest -Method GET -Path "git/tags/$($ref.object.sha)"
        if ($annotation.message -cne $marker -or $annotation.object.type -cne 'commit' -or
            $annotation.object.sha -cne $plan.CommitSha -or $annotation.tag -cne $plan.Version) {
            throw 'The existing version tag is not owned by this PR. Refusing to overwrite it.'
        }
    }

    $version = $plan.Version
    $release = Invoke-ReleaseRequest -Method GET -Path "releases/tags/$version" -AllowNotFound
    if ($null -ne $release) {
        if ($existingTags.Count -ne 1 -or $release.tag_name -cne $version -or
            $release.name -cne $version -or $release.body -cne $plan.Body -or
            $release.draft -ne $false -or $release.prerelease -ne $false) {
            throw "Release $version already exists with different ownership or content. Refusing to overwrite it."
        }
        Write-Verbose "Release $version already matches PR #$($plan.PullRequestNumber); no changes needed."
        $plan
        return
    }

    if (-not $PSCmdlet.ShouldProcess("ClaweOfTheWild/Wild PR #$($plan.PullRequestNumber)", "Publish $version")) {
        return
    }
    if ($existingTags.Count -eq 0) {
        $annotation = Invoke-ReleaseRequest -Method POST -Path 'git/tags' -Body @{
            tag = $version
            message = $marker
            object = $plan.CommitSha
            type = 'commit'
        }
        # Ref creation is atomic. A competing reservation fails, never overwrites.
        $null = Invoke-ReleaseRequest -Method POST -Path 'git/refs' -Body @{
            ref = "refs/tags/$version"
            sha = $annotation.sha
        }
    }
    $null = Invoke-ReleaseRequest -Method POST -Path 'releases' -Body @{
        tag_name = $version
        target_commitish = $plan.CommitSha
        name = $version
        body = $plan.Body
        draft = $false
        prerelease = $false
        generate_release_notes = $false
        make_latest = 'legacy'
    }
    Write-Verbose "Published $version for PR #$($plan.PullRequestNumber) at $($plan.CommitSha)."
    $plan
}

Export-ModuleMember -Function Get-ReleasePlan, Publish-MergedPullRequestRelease
